title: Applichem
email: your-email@example.com
description: >-
  Building Solution Provider - Waterproofing, Concrete Repair,
  Structural Strengthening, Epoxy Coating, Heat Proofing & More.
baseurl: "/Applichem"
url: "https://fahadhassan315.github.io"
author: Applichem
lang: en
timezone: Asia/Karachi
github_username: FahadHassan315

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - _posts/TEMPLATE-blog-post.md
